# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'YAML Pipeline Web App/YAML Pipeline Web App.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: false
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption Active(be5282a4-2cfe-47d1-a1e6-8f3f862d5874)'
    appType: 'webApp'
    appName: 'YAMLPipelineWebApp56687'
    package: '$(Build.ArtifactStagingDirectory)'
    deploymentMethod: 'auto'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'webapp'
    publishLocation: 'pipeline'

    